<a href="https://colab.research.google.com/github/sofieostrau/Data_Science_ESA4/blob/main/DataScience_Sofie_Ostrau_Aufgabe4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Hier ist der Beginn meines Codes

# Aufgabe 1: Jupiternotebook ausprobieren

Für diese Aufgabe habe ich mich anhand einiger Beispiele aus dem Script orientiert.

In [ ]:


print("Hallo Datascientists")


Hallo Datascientists


Hier kommen weitere **Codebeispiele**


In [ ]:
count= 123+28
print(count)

151


In [ ]:
i =1
while i<8:
  print(i)
  i+=1

1
2
3
4
5
6
7


In [ ]:
string="Datascience"
print(string[0])
print(string[3:5])


D
as


In [ ]:
tiere = ["Katze", "Vogel", "Hund", "Maus"]
wert_tiere=tiere[0]
print(wert_tiere)
länge=len(tiere)
print(länge)

Katze
4


# Aufgabe 2: 101 Numpy Exercises

Für diese Aufgabe habe ich zunächst die Aufgabe gelesen und versucht diese selbst zu lösen. Anschließend habe ich mir die Lösungen angeschaut und versucht diese nachzuvollziehen. 

In [ ]:
#Aufgabe 1
import numpy as np 
print(np.__version__)

1.19.5


In [ ]:
#Aufgabe 2
array = np.array([0,1,2,3,4,5,6,7,8,9]) 
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Aufgabe 3
np.ones((3,3), dtype=bool) 



array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
#Aufgabe 4, funktioniert nicht ganz
array = np.array([0,1,2,3,4,5,6,7,8,9]) 
if array%2==1
    print(array)



SyntaxError: ignored

In [ ]:
 #Aufgabe 5
array = np.where(array%2, -1, array)
print(array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
#Aufgabe 6
mein_array = np.array([0,1,2,3,4,5,6,7,8,9]) 
neues_array = np.where(mein_array %2==1,-1,mein_array)
print(neues_array)


[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
#Aufgabe 7
np.reshape(array,(2,5))



array([[ 0, -1,  2, -1,  4],
       [-1,  6, -1,  8, -1]])

In [ ]:
#Aufgabe 8
array_a = np.arange(10).reshape(2,-1)
array_b = np.repeat(1, 10).reshape(2,-1)
print(array_a)
print(array_b)
np.vstack((array_a,array_b))


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
#Aufgabe 9
array_a = np.arange(10).reshape(2,-1)
array_b = np.repeat(1, 10).reshape(2,-1)
print(array_a)
print(array_b)
np.hstack((array_a,array_b))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [ ]:
#Aufgabe 10
array_wiederholungen = np.array([1,2,3])
print(array_wiederholungen)
np.repeat(array_wiederholungen,3)
np.tile(array_wiederholungen,(1,3))

[1 2 3]


array([[1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [ ]:
#Aufgabe 11
erstes_array = np.array([1,2,3,2,3,4,3,4,5,6])
zweites_array = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(erstes_array, zweites_array))

[2 4]


In [ ]:
#Aufgabe 12
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)


array([1, 2, 3, 4])

In [ ]:
#Aufgabe 13
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(array1==array2)

(array([1, 3, 5, 7]),)

In [ ]:
#Aufgabe 14
neuesarray = np.array([2, 6, 1, 9, 10, 3, 27])
#print("Values bigger than 10 =", neuesarray[neuesarray<5 && neunesarray>10])
newArr = neuesarray[(neuesarray > 5) & (neuesarray <= 10)]
print(newArr)

[ 6  9 10]


In [ ]:
#Aufgabe 15, funktioniert nicht ganz
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

def pair_maxx(a, b):
    """Get the maximum of two items"""
    a = np.array([5, 7, 9, 8, 6, 4, 5])
    b = np.array([6, 3, 4, 8, 9, 7, 1])
    if a >= b:
        return a
    else:
        return b
pair_maxx(a, b)

ValueError: ignored

In [ ]:
#Aufgabe 16, funktioniert nicht ganz

arrchange = np.arange(9).reshape(3,3)
print(arrchange)
arrchange[0, 1] = arrchange[1, 0]
print(arrchange)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
einarray = np.arange(9).reshape(3,3)
einarray[[1,0,2], :]
print(einarray)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Aufgabe 18

array_reverse = np.arange(9).reshape(3,3)
array_reverse[ : :-1]




array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [ ]:
#Aufgabe 19
arr_reverse = np.arange(9).reshape(3,3)
arr_reverse[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [ ]:
#Aufgabe 20
einArray = np.arange(9).reshape(3,3)
randomarray = np.random.uniform(5,10, size=(5,3))
print(randomarray)

[[8.18464832 5.16353871 5.59671305]
 [5.4341549  9.48480153 8.54802998]
 [6.15213092 9.02637269 7.98126998]
 [5.70380578 8.65980984 7.9464703 ]
 [7.1536051  6.71702409 9.39265289]]


In [ ]:
#Aufgabe 21
random_decimal_array = np.random.random((5,3))
np.set_printoptions(precision=3)
print(random_decimal_array)

[[0.616 0.713 0.363]
 [0.512 0.463 0.341]
 [0.301 0.904 0.981]
 [0.966 0.773 0.452]
 [0.37  0.466 0.285]]


In [ ]:
#Aufgabe 22
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
print(rand_arr)
#np.set_printoptions(suppress=True)
np.set_printoptions(suppress=False)
print(rand_arr)

[[0.001 0.    0.   ]
 [0.001 0.    0.   ]
 [0.001 0.001 0.   ]]
[[5.434e-04 2.784e-04 4.245e-04]
 [8.448e-04 4.719e-06 1.216e-04]
 [6.707e-04 8.259e-04 1.367e-04]]


In [ ]:
#Aufgabe 23 muss nochmal genauer verstanden werden
a_limit = np.arange(15)
#np.clip(a_limit, 1, 6)
np.set_printoptions(threshold=6)
print(a_limit)

[ 0  1  2 ... 12 13 14]


In [ ]:
#Aufgabe 24, funktioniert nicht ganz
another_limit = np.arange(15)
np.set_printoptions(threshold=6)
np.set_printoptions(threshold=np.non-nan)
print(another_limit)

AttributeError: ignored

In [ ]:
#Aufgabe 25

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
namen = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

# Print the first 3 rows
iris[:3]
#> array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
#>        [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
#>        [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

# Aufgabe 3: Do the following exercise in a Jupyter Notebook

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/edlich/eternalrepo/master/DS-WAHLFACH/countries.csv"
df = pd.read_csv(url)
print("Originler Datensatz")
print (df)

#Show last 4 rows
print("Letzte 4 Reihen")

print(df.tail(4))

#Show all the row of countries who have the EURO
print("Alle EURO-Länder")
print(df[df['Currency']== 'EUR'])

#Show only name and Currency in a new data frame
print("Nur Name und Währung")
print(df[['Name', 'Currency']])

#Show only the rows/countries that have more than 2000 BIP 
print("BIP größer als 2000")
bruttoinlands= df[df["BIP"] > 2000]
print(bruttoinlands)

#Select all countries where with inhabitants between 50 and 150 Mio
print("Einwohner zwischen 50 und 150 Mio")
print(df[df["People"].between(50000000, 150000000)])

#Change BIP to Bip
print("Neue Schreibweise")
print(df.rename(columns={"BIP" : "bip"}))

#Sum of Bip
print("Summe aller bip")
summe= df['BIP'].sum()
print(summe)


#Calculate the average people of all countries
print("Durchschnitt aller Einwohner")
df_mean = df["People"].mean()
print(df_mean)

#Sort by name alphabetically
print("Alphabethisch sortieren")
print(df.sort_values(by='Name'))

#Create a new Data frame
print('Neuer Datensatz')
df2 = df.copy()
print(df2)
df2.loc[df2['Area'] > 1000000] = df2.rename(columns={"Area" : "AREA"})

print(df2)  
  
	









Originler Datensatz
       Name     People     Area   BIP Currency
0   Germany   82521653   357385  3466      EUR
1     Japan  126045000   377835  4938      YEN
2    Canada   36503097  9984670  1529      CAD
3     Italy   60501718   301338  1850      EUR
4  Brazilia  208360000  8515770  1798     REAL
Letzte 4 Reihen
       Name     People     Area   BIP Currency
1     Japan  126045000   377835  4938      YEN
2    Canada   36503097  9984670  1529      CAD
3     Italy   60501718   301338  1850      EUR
4  Brazilia  208360000  8515770  1798     REAL
Alle EURO-Länder
      Name    People    Area   BIP Currency
0  Germany  82521653  357385  3466      EUR
3    Italy  60501718  301338  1850      EUR
Nur Name und Währung
       Name Currency
0   Germany      EUR
1     Japan      YEN
2    Canada      CAD
3     Italy      EUR
4  Brazilia     REAL
BIP größer als 2000
      Name     People    Area   BIP Currency
0  Germany   82521653  357385  3466      EUR
1    Japan  126045000  377835  4938      